"""add admin totp fields

Revision ID: 08f5069d2cbb
Revises: 504edb390d29
Create Date: 2026-08-05 16:53:24.496123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f5069d2cbb'
down_revision = '504edb390d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added -- same reasoning as the sibling 'active' column
    # migration right before this one in the chain (504edb390d29): a bare
    # NOT NULL ADD COLUMN with no default fails against Postgres the
    # moment the admin table is non-empty. False matches
    # Admin.totp_enabled's own model-level default (see app.py) -- an
    # admin account created before 2FA existed correctly starts with it
    # off, not enrolled.
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
