"""add user_session table

Revision ID: 4862a1c653b3
Revises: 15df48c6ccfd
Create Date: 2026-08-11 22:44:59.265781

Autogenerate only saw the routine job_fts* false-positive diff (stripped
per this chain's standing convention -- the FTS5 virtual table isn't
ORM-tracked, so it always shows up as a phantom "removed table" and is
never actually touched here) -- it missed the real schema change entirely
because the dev server's own db.create_all() had already silently created
user_session on file-reload before this command ran (SKIP_DB_CREATE_ALL
only guards the `flask db migrate` process itself, not the already-running
app server). Hand-written to match UserSession in app.py exactly, so this
migration is what actually creates the table on a fresh database or in
production, same as it would have autogenerated if the timing had been
different.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4862a1c653b3'
down_revision = '15df48c6ccfd'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'user_session',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('channel', sa.String(length=10), nullable=False),
        sa.Column('session_token', sa.String(length=64), nullable=False),
        sa.Column('device_label', sa.String(length=200), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_seen_at', sa.DateTime(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('session_token'),
    )
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_session_session_token'), ['session_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_session_user_id'), ['user_id'], unique=False)


def downgrade():
    op.drop_table('user_session')
