"""add admin.active column

Revision ID: 504edb390d29
Revises: 1dab0063c563
Create Date: 2026-08-05 16:44:42.298863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504edb390d29'
down_revision = '1dab0063c563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added (real gap found via a full-codebase review): a
    # bare NOT NULL ADD COLUMN with no default fails immediately against
    # Postgres the moment the admin table has any existing row — which it
    # always will in a real deployment, since scripts/create_admin.py is
    # the only way to create one. True matches the Admin.active column's
    # own model-level default (see app.py) and the correct behavior: an
    # admin account that existed before this migration should stay active,
    # not be silently locked out by a schema change.
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
