"""add job_fts fts5 virtual table

Revision ID: bc0adf755ad8
Revises: 08f5069d2cbb
Create Date: 2026-08-05 17:18:46.896050

Hand-written, not autogenerated — Alembic's autogenerate compares against
SQLAlchemy models, and job_fts is a raw FTS5 virtual table with no ORM
model of its own (see the Job.after_insert listener in app.py, which is
what keeps it in sync going forward). SQLite-only: guarded by a dialect
check so this is a correct no-op on Postgres, which uses a real
to_tsvector/ts_rank query computed directly against the job table instead
(see get_jobs() in app.py) and needs no shadow table at all.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0adf755ad8'
down_revision = '08f5069d2cbb'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":
        return

    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS job_fts USING fts5("
        "title, required_skills, location, content=''"
        ")"
    )
    # Backfill from any jobs that already existed before this migration
    # ran (seeded demo jobs, jobs created before this feature existed) —
    # the after_insert listener only covers jobs created from this point
    # forward.
    op.execute(
        "INSERT INTO job_fts(rowid, title, required_skills, location) "
        "SELECT id, title, required_skills, location FROM job"
    )


def downgrade():
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":
        return
    op.execute("DROP TABLE IF EXISTS job_fts")
