"""add message read receipts and attachment

Revision ID: bdeaf53f4c4b
Revises: bc0adf755ad8
Create Date: 2026-08-05 17:31:06.126344

Hand-edited after autogeneration: Alembic's autogenerate diffed against
SQLAlchemy's model metadata, which has no entry for job_fts (a raw FTS5
virtual table, not an ORM model — see the previous migration) or its
SQLite-managed internal shadow tables (job_fts_data/_config/_docsize/_idx).
It therefore proposed dropping all of them, which would have silently
destroyed the full-text search index. Removed those erroneous
drop_table/create_table calls, keeping only the real Message column
additions this migration is actually for.

Also added server_default=sa.false() on the new `read` column (not
autogenerated) — without it, backfilling this NOT NULL column onto any
database with pre-existing Message rows would fail outright; a Python-level
model default only applies to new INSERTs, not a migration's own backfill.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdeaf53f4c4b'
down_revision = 'bc0adf755ad8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attachment_file', sa.String(length=300), nullable=True))


def downgrade():
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('attachment_file')
        batch_op.drop_column('read_at')
        batch_op.drop_column('read')
