"""add employer verification fields

Revision ID: c0f4192abf29
Revises: bdeaf53f4c4b
Create Date: 2026-08-05 18:03:09.490708

Hand-edited after autogeneration: same recurring false-positive already
explained in the job_fts and message-read-receipts migrations — Alembic's
autogenerate has no model for the hand-written FTS5 virtual table and
proposed dropping it and its SQLite-managed shadow tables. Removed those.
Also added server_default='unverified' on the new NOT NULL
verification_status column (not autogenerated) so backfilling it onto any
database with pre-existing Employer rows doesn't fail outright.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f4192abf29'
down_revision = 'bdeaf53f4c4b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), nullable=False, server_default='unverified'))
        batch_op.add_column(sa.Column('verification_document', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('verification_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_reviewed_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_employer_verification_reviewed_by_admin_id', 'admin', ['verification_reviewed_by_admin_id'], ['id'])


def downgrade():
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employer_verification_reviewed_by_admin_id', type_='foreignkey')
        batch_op.drop_column('verification_reviewed_by_admin_id')
        batch_op.drop_column('verification_reviewed_at')
        batch_op.drop_column('verification_document')
        batch_op.drop_column('verification_status')
